# Generated by Django 5.1.2 on 2024-10-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='estado',
            field=models.CharField(choices=[('a_fazer', 'A Fazer'), ('em_progresso', 'Em Progresso'), ('concluido', 'Concluído')], default='a_fazer', max_length=20),
        ),
    ]
