# Generated by Django 5.1.2 on 2024-11-04 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_tarefa_estado'),
        ('trabalhos', '0006_alter_trabalho_teve_proposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='cliente',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='trabalho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='trabalhos.trabalho'),
            preserve_default=False,
        ),
    ]
