# Generated by Django 5.1.2 on 2024-10-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('extensao', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('expirado', 'Expirado'), ('terminado', 'Terminado')], max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateField()),
            ],
        ),
    ]
