# Generated by Django 4.2.16 on 2024-10-22 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('dominios', '0003_dominio_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominio',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominios_dominio', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='dominio',
            name='data_criacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dominio',
            name='data_expiracao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dominio',
            name='extensao',
            field=models.CharField(choices=[('.com', '.com'), ('.pt', '.pt'), ('.net', '.net'), ('.org', '.org'), ('.bizz', '.bizz')], max_length=10),
        ),
    ]
