# Generated by Django 5.1.2 on 2024-11-02 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('prazo', models.DateField()),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('em_processo', 'Em Processo'), ('entregue', 'Entregue'), ('aprovada', 'Aprovada'), ('sem_resposta', 'Sem Resposta')], default='solicitada', max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='propostas_pdfs/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='clientes.cliente')),
            ],
        ),
    ]
