# Generated by Django 5.1.2 on 2024-11-03 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('trabalhos', '0002_proposta_data_entrega_proposta_data_expiracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('prazo', models.DateField()),
                ('tipo_trabalho', models.CharField(choices=[('web', 'Web'), ('design', 'Design'), ('consultoria', 'Consultoria')], max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=10)),
                ('estado_trabalho', models.CharField(choices=[('standby', 'Standby'), ('iniciado', 'Iniciado'), ('concluido', 'Concluído')], default='standby', max_length=20)),
                ('teve_proposta', models.BooleanField(default=False)),
                ('numero_proposta', models.CharField(blank=True, max_length=20, null=True)),
                ('pdf_proposta', models.FileField(blank=True, null=True, upload_to='trabalhos_pdfs/')),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('validade_em_dias', models.PositiveIntegerField(default=30)),
                ('data_expiracao', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabalhos', to='clientes.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Proposta',
        ),
    ]
