# Generated by Django 5.1.2 on 2024-11-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0003_trabalho_delete_proposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='prazo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='prioridade',
            field=models.CharField(blank=True, choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='teve_proposta',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
