# Generated by Django 5.1.2 on 2024-11-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0004_alter_trabalho_data_inicio_alter_trabalho_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='prazo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
