# Generated by Django 5.1.2 on 2024-11-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0005_alter_trabalho_prazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='teve_proposta',
            field=models.BooleanField(default=False),
        ),
    ]
